### ISSUE TITLE
Interested to work in the Blockchain space?

### ISSUE THREAD

**Issue by rohanagarwal94** [brc-dd/brc-dd#1]
Hello,
I am Rohan. Unfortunately, I could not fidn your public profile writing it as an issue. We at Cypherock are working at the intersection of Blockchain, Embedded, Cryptography, and security on a World's first product. You can read more @ - https://angel.co/company/cypherock-wallet. If this interests you, let me know and we can talk about work together in some capacity. We have C dev roles majorly.

Best,
Rohan
Cypherock

**Comment by brc-dd** [comment]
Hello Rohan! While your product seems interesting, I am currently not actively looking for any job/internship. Also, I don't have much prior experience in blockchain and cryptography technologies. Sadly, I'll have to decline your offer. I hope you'll find your perfect candidate soon. Would you mind connecting on LinkedIn? I've just sent an invitation.
